# AI Stock Trading Companion - Production Docker Compose
# Use this for production deployments with additional services

version: '3.8'

services:
  stock-trader-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-trader-ai:latest
    container_name: stock-trader-ai-production
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Override these in production
      - NEXT_PUBLIC_FINNHUB_API_KEY=${NEXT_PUBLIC_FINNHUB_API_KEY}
      - NEXT_PUBLIC_GEMINI_API_KEY=${NEXT_PUBLIC_GEMINI_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://your-domain.com}
      - USER_PASSWORD_HASH=${USER_PASSWORD_HASH}
    volumes:
      - stock-trader-data:/app/data
    networks:
      - stock-trader-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/test-env', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: stock-trader-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - stock-trader-ai
    networks:
      - stock-trader-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis:
    image: redis:7-alpine
    container_name: stock-trader-redis
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - stock-trader-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Optional: Monitoring with Watchtower for auto-updates
  watchtower:
    image: containrrr/watchtower
    container_name: stock-trader-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Check every hour
    command: --interval 3600 stock-trader-ai-production

volumes:
  stock-trader-data:
    driver: local
  redis-data:
    driver: local
  nginx-cache:
    driver: local

networks:
  stock-trader-network:
    driver: bridge